商品详情
---
tags:
  - product
parameters:
  - name: code
    in: path
    default: 5cTJxqUoUPXmucpTPni9ZL
responses:
  200:
    description: description
    schema:
      type: object
      properties:
        code:
          type: string
          enum: ['success','not.exist']
          description: ''